### ISSUE TITLE
Stackoverflow on line 590 in BitcoinJSONRPCClient.java when retrieving type of scriptpubkey

### ISSUE THREAD

**Issue by Shtutnik** [Polve/JavaBitcoindRpcClient#1]
I think there is a typo in this function:
        @Override
        public String type() {
            return mapStr(type());                   <====== typo?
        }

I think it should be:

        return mapStr("type");

**Comment by Polve** [comment]
Indeed! Fixed in version 0.9.5.

Thanks very much for reporting the problem.
