### ISSUE TITLE
Add support for OP_RETURN data

### ISSUE THREAD

**Issue by mfarnoosh** [Polve/JavaBitcoindRpcClient#19]
Can not find any way to create raw transaction which has data in it's output list.
in bitcoin command, data can insert as one of outputs. e.g.
{
	"mgt9WNsoi7pPY29ACTuWPVX73XGFVhD9Vi": 40,
	"data": "ba3885e9aa5fd0949f40dc5d7905700fa039ef8ad425c60479cc52dfe16aa3e8"
}

but here amount of TxOut in double and can not use as String data.

Sorry, can not find any better way to contact.
if i missed something and there is a way in JavaBitcoindRpcClient, guide me to that.

**Comment by Polve** [comment]
Can you please provide a couple of complete examples of inputs and outputs so that I can create a test case?

**Comment by mfarnoosh** [comment]
copy below line and run createrawtransaction command in bitcoind console window:
"[{
		\"txid\": \"7ca77b7899e037d92e6ba36c88573a40b75bfec6586deea1ef14ced8526e26ec\",
		\"vout\":0
	}
]"

"{
	\"mkyqtevhVKz3TfrS2XEgoHJ7rKq31S9KsT\":49.99900000,
	\"data\":\"78f8204c8223b238d46ff81a590f8c5334ab51c0da37f7b05e6c7ceeed3fafad\"
}"

this will create a transaction which the hex data 78f8204c8223b238d46ff81a590f8c5334ab51c0da37f7b05e6c7ceeed3fafad (that is SHA256 hash of real content) stored in it.
now i wanted this operatoin in java but in Output class amount is always double!

so i extended your file with two new class ExtendedTxOut, ExtendedBitcoinJSONRPCClient.
in ExtendedTxOut  i added a 'boolean isData''
in ExtendedBitcoinJSONRPCClient i wrote a new function  called: 'createExtendedRawTransaction' exactly like createRawTransaction function which this new function accept ExtendedTxOut instead of TxOut.
and check the isData variable and if that was true 
put  "data":"ADDRESS(HEX_VALUE)" 
instead of old style "ADDRESS":"AMOUNT"

i try to change minimum rather than original source to prevent extra BUGs

i can push my codes here to share and improve it.

thanks

**Comment by tdiesler** [comment]
Done in branch 0.17.x
