### ISSUE TITLE
Move operation returns boolean, not string

### ISSUE THREAD

**Issue by docmanni** [Polve/JavaBitcoindRpcClient#23]
When I try to move funds from one account to another, I get an exception that boolean cannot be converted to string. Checking the result map in loadResponse, it shows "result" -> "true".

**Comment by Polve** [comment]
I'm not able to test because of lacking framework.
Could you please verify that just changing result types in BitcoindRpcClient lines 710-714 and lines 1613-1624 in BitcoinJSONRPCClient fixes the problem for you?
This way I'll commit the fix (or just approve your pull request).

**Comment by docmanni** [comment]
Yes, I can confirm that this change works. I have changed the types to Boolean and it all works well. However, before I commit those changes, I'd like to add that I'm currently only working in "testnet" mode, I don't know if this has some effect and the production mode of the bitcoin daemon will behave differently. Do you have any experience with that?

**Comment by Polve** [comment]
There should be no difference at all: go ahead and create a pull request with your changes!

**Comment by docmanni** [comment]
I'm afraid I don't have the right to create a new branch, it's my first time on github to commit such change. ;-)

**Comment by Polve** [comment]
https://help.github.com/articles/creating-a-pull-request/
