### ISSUE TITLE
Case Sensitivity: BitcoinRpcException vs BitcoinRPCException

### ISSUE THREAD

**Issue by efritze** [Polve/JavaBitcoindRpcClient#25]
Can't compile on Mac or Windows because the two classes (BitcoinRpcExtension and BitcoinRPCException) have the same name, in the same package, but with different cases.

BitcoinRPCException should be renamed to avoid conflicts with BitcoinRpcException.

**Comment by xhliu** [comment]
Having the same issue on Mac.
