### ISSUE TITLE
getNewAddress does not create account with 0.00 BTC balance

### ISSUE THREAD

**Issue by ghost** [Polve/JavaBitcoindRpcClient#27]
When i execute below code it create a account with this email: myemail@gmail.com . 
```
BitcoinJSONRPCClient bitcoin = new BitcoinJSONRPCClient(url);
String address = bitcoin.getNewAddress("myemail@gmail.com");
```
when i execute `bitcoin-cli listaccounts` in my terminal. I can see account created with my email but i  can see some default balance in it . Here is the listaccounts output:

```
{
  "": -0.55385912,
  "myemail@gmail.com": 1.11942880,
}
```
I want when ever i call `getNewAddress` method it should create account with 0 BTC balance

**Comment by tdiesler** [comment]
The account API in bitcoin core is deprecated and will get removed in 0.18.0
