### ISSUE TITLE
sendToAddress method

### ISSUE THREAD

**Issue by bareq** [Polve/JavaBitcoindRpcClient#6]
You shouldn't keep amount in double. I suggest long in satoshi (like in BitcoinJ) or BigDecimal.

**Comment by Polve** [comment]
I know, it was the choice of the original implementor.
I'm leaning toward BigDecimal, but it's a bit of refactor and it breaks compatibility so I need to think about it

**Comment by tdiesler** [comment]
Yes, this needs to be done - but is also an incompatible change.
Please, try #50 on branch [0.17.x](https://github.com/Polve/JavaBitcoindRpcClient/tree/0.17.x)
