### ISSUE TITLE
Propose a versioning scheme for this library

### ISSUE THREAD

**Issue by tdiesler** [Polve/JavaBitcoindRpcClient#69]
Also see PR #48 

We have a few incompatible changes lined up in branch 0.17.x. Now that this version of bitcoin core has been [released](https://github.com/bitcoin/bitcoin/releases/tag/v0.17.0), it is time to bring them in to master.

The question however arises what the next version should be. I propose a [semantic versioning](https://semver.org/) scheme, where an incompatible API change would call for a major version bump.

The next version would therefore be 1.0.0

**Comment by Polve** [comment]
I agree with semantic versioning, it's ok to publish next version (the one which gets rid of doubles) as 1.0.0

**Comment by tdiesler** [comment]
merci
