### ISSUE TITLE
signrawtransaction complete support

### ISSUE THREAD

**Issue by fmontoto** [Polve/JavaBitcoindRpcClient#7]
Hi! I couldn't find how to pass to signrawtransaction all the parameter options it supports [now](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list). I'm mostly interested in validating transactions without boradcast them, as stated [here](https://en.bitcoin.it/wiki/Raw_Transactions#Validate_a_transaction_without_broadcasting_it). Are you still working in the library? Can you add it? Can I send a PR?
Thanks!

**Comment by Polve** [comment]
Hi!
I'm in maintenance mode because I've not much time, happy to receive a PR!

I wrote an initial support in this branch, but I'm not able to test it, feel free to use it as a starting point: https://github.com/Polve/JavaBitcoindRpcClient/tree/new-signraw-tx

**Comment by fmontoto** [comment]
Ok, I'll take a look, thank you!

**Comment by fmontoto** [comment]
closed by #13
