### ISSUE TITLE
Change artifactId to a standard format

### ISSUE THREAD

**Issue by tdiesler** [Polve/JavaBitcoindRpcClient#87]
Perhaps like this

```
JavaBitcoindRpcClient => java-bitcoin-client
```

The repo name on github may then also want to change. 

PS: most jars have a lower case name with dashes

**Comment by Polve** [comment]
I know, I left the original name when inherited the package from the original author.

I would prefer java-rpc-client or something with the "rpc" word in it, WDYT?

**Comment by tdiesler** [comment]
```
java-bitcoin-jsonrpc-client
java-bitcoin-rpc-client
java-btc-rpc-client
```

**Comment by Polve** [comment]
bitcoin-rpc-client is fine for me

**Comment by tdiesler** [comment]
ok
